import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Category, FoodItem } from '../core/models/models';
import { ApiService } from '../core/services/api.service';
import { AuthService } from '../core/services/auth.service';
import { ToastService } from '../core/services/toast.service';
@Component({imports:[FormsModule],template:`
<section class="page-hero small"><div class="container"><span class="eyebrow">RESTAURANT OWNER</span><h1>Menu management</h1></div></section><section class="section container">
@if(!restaurantId){<div class="empty">🏪<h2>Register your restaurant first</h2><a class="btn" href="/owner/restaurant">Register restaurant</a></div>}@else{
<div class="toolbar"><input [(ngModel)]="search" (keyup.enter)="loadFoods()" placeholder="Search menu"><button class="btn" (click)="showForm.set(!showForm())">{{showForm()?'Close':'Add food'}}</button></div>
@if(showForm()){<form class="panel editor" (ngSubmit)="save()"><h2>Add a menu item</h2><div class="form-grid"><label>Name<input [(ngModel)]="draft.name" name="name" required></label><label>Category<select [(ngModel)]="draft.category" name="category" required>@for(c of categories();track c.id){<option [ngValue]="c.id">{{c.name}}</option>}</select></label><label>Original price<input type="number" [(ngModel)]="draft.original_price" name="price" required></label><label>Discount price<input type="number" [(ngModel)]="draft.discount_price" name="discount"></label><label class="span-2">Description<textarea [(ngModel)]="draft.description" name="description"></textarea></label><label class="check"><input type="checkbox" [(ngModel)]="draft.is_vegetarian" name="veg"> Vegetarian</label><label class="check"><input type="checkbox" [(ngModel)]="draft.is_available" name="available"> Available</label></div><button class="btn">Save item</button></form>}
<div class="panel table-wrap"><table><thead><tr><th>Item</th><th>Category</th><th>Price</th><th>Type</th><th>Available</th><th></th></tr></thead><tbody>@for(f of foods();track f.id){<tr><td><b>{{f.name}}</b><small>{{f.description}}</small></td><td>{{f.category_name}}</td><td>₹{{f.price}}</td><td>{{f.is_vegetarian?'Veg':'Non-veg'}}</td><td><button class="toggle" [class.on]="f.is_available" (click)="toggle(f)"><i></i></button></td><td><button class="icon-button danger" (click)="remove(f)">×</button></td></tr>}</tbody></table></div>}
</section>`})
export class MenuManagementComponent implements OnInit{restaurantId=0;foods=signal<FoodItem[]>([]);categories=signal<Category[]>([]);showForm=signal(false);search='';draft:Partial<FoodItem>={name:'',description:'',original_price:'',discount_price:undefined,is_vegetarian:true,is_available:true,preparation_time:20};constructor(private api:ApiService,private auth:AuthService,private toast:ToastService){}ngOnInit(){this.api.restaurants().subscribe(v=>{const r=v.results.find(x=>x.owner===this.auth.user()?.id);if(r){this.restaurantId=r.id;this.api.categories({restaurant:r.id}).subscribe(c=>{this.categories.set(c.results);this.draft.category=c.results[0]?.id;});this.loadFoods();}});}loadFoods(){this.api.foods({restaurant:this.restaurantId,search:this.search}).subscribe(v=>this.foods.set(v.results));}save(){this.draft.restaurant=this.restaurantId;this.api.createFood(this.draft).subscribe(()=>{this.toast.show('Food item created');this.showForm.set(false);this.loadFoods();});}toggle(f:FoodItem){this.api.updateFood(f.id,{is_available:!f.is_available}).subscribe(()=>{this.toast.show('Availability updated');this.loadFoods();});}remove(f:FoodItem){if(confirm(`Delete ${f.name}?`))this.api.deleteFood(f.id).subscribe(()=>this.loadFoods());}}
