import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { Cart, FoodItem } from '../core/models/models';
import { ApiService } from '../core/services/api.service';
import { ToastService } from '../core/services/toast.service';
import { LoadingComponent } from '../shared/components/loading';
@Component({imports:[FormsModule,RouterLink,LoadingComponent],template:`<section class="page-hero small"><div class="container"><span class="eyebrow">YOUR ORDER</span><h1>Cart</h1></div></section><section class="section container">@if(loading()){<app-loading/>}@else if(!cart()?.items?.length){<div class="empty">🛒<h2>Your cart is empty</h2><p>Add something delicious to get started.</p><a routerLink="/restaurants" class="btn">Browse restaurants</a></div>}@else if(cart();as c){<div class="checkout-grid"><div class="panel"><div class="section-head"><h2>Your items</h2><button class="link-button danger" (click)="clear()">Clear cart</button></div>@for(item of c.items;track item.id){<div class="cart-row"><div class="food-icon small-icon"><img [src]="foodImage(item.food)" [alt]="item.food.name"></div><div class="grow"><b>{{item.food.name}}</b><small>₹{{item.unit_price}} each</small></div><div class="qty"><button (click)="quantity(item.id,item.quantity-1)">−</button><span>{{item.quantity}}</span><button (click)="quantity(item.id,item.quantity+1)">+</button></div><b>₹{{item.subtotal}}</b><button class="icon-button" (click)="remove(item.id)" aria-label="Remove">×</button></div>}</div><aside class="summary"><h2>Order summary</h2><div><span>Subtotal</span><b>₹{{c.subtotal}}</b></div><div><span>Tax</span><b>₹{{c.tax}}</b></div><div><span>Delivery</span><b>₹{{c.delivery_fee}}</b></div>@if(c.discount){<div class="discount"><span>Discount</span><b>−₹{{c.discount}}</b></div>}<form class="coupon" (ngSubmit)="applyCoupon()"><input [(ngModel)]="coupon" name="coupon" placeholder="Coupon code"><button>Apply</button></form><div class="total"><span>Total</span><b>₹{{c.grand_total}}</b></div><button class="btn full" (click)="checkout()">Continue to checkout</button></aside></div>}</section>`})
export class CartComponent implements OnInit{cart=signal<Cart|null>(null);loading=signal(true);coupon='';private readonly categoryImages:Record<string,string>={'Biryani':'/images/food/chicken-biryani.webp','Pizza':'/images/food/margherita-pizza.webp','Burger':'/images/food/burger.webp','Fast Food':'/images/food/burger.webp','Chinese':'/images/food/chinese.webp','South Indian':'/images/food/south-indian.webp','North Indian':'/images/food/north-indian.webp','Desserts':'/images/food/desserts.webp','Beverages':'/images/food/drinks.webp','Seafood':'/images/food/seafood.webp'};constructor(private api:ApiService,private router:Router,private toast:ToastService){}ngOnInit(){this.load();}foodImage(food:FoodItem){return food.image||this.categoryImages[food.category_name]||'/images/food/veg-biryani.webp';}load(){this.api.cart().subscribe({next:v=>{this.cart.set(v);this.loading.set(false)},error:()=>this.loading.set(false)});}quantity(id:number,q:number){if(q<1){this.remove(id);return;}this.api.updateCartItem(id,q).subscribe(()=>this.load());}remove(id:number){if(confirm('Remove this cart item?'))this.api.removeCartItem(id).subscribe(()=>{this.toast.show('Item removed','info');this.load();});}clear(){if(confirm('Clear your cart?'))this.api.clearCart().subscribe(()=>this.load());}applyCoupon(){this.api.applyCoupon(this.coupon).subscribe(v=>{this.toast.show(`Coupon ${v.coupon} applied`);this.load();});}checkout(){void this.router.navigateByUrl('/checkout');}}
