import { DatePipe } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Order, Review } from '../core/models/models';
import { ApiService } from '../core/services/api.service';
import { AuthService } from '../core/services/auth.service';
import { ToastService } from '../core/services/toast.service';
@Component({imports:[DatePipe,FormsModule],template:`<section class="page-hero small"><div class="container"><span class="eyebrow">YOUR VOICE</span><h1>Reviews</h1></div></section><section class="section narrow"><form class="panel" (ngSubmit)="save()"><h2>Review a delivered order</h2><label>Order<select [(ngModel)]="draft.order" name="order" required><option [ngValue]="undefined">Select order</option>@for(o of eligible();track o.id){<option [ngValue]="o.id">{{o.restaurant_name}} — {{o.order_number}}</option>}</select></label><label>Rating<select [(ngModel)]="draft.rating" name="rating"><option [ngValue]="5">5 — Excellent</option><option [ngValue]="4">4 — Good</option><option [ngValue]="3">3 — Okay</option><option [ngValue]="2">2 — Poor</option><option [ngValue]="1">1 — Very poor</option></select></label><label>Comment<textarea [(ngModel)]="draft.comment" name="comment" placeholder="What did you enjoy?"></textarea></label><button class="btn" [disabled]="!draft.order">{{editingId?'Update review':'Submit review'}}</button></form><div class="panel">@for(r of reviews();track r.id){<article class="review"><div class="stars">{{stars(r.rating)}}</div><p>{{r.comment||'No written comment.'}}</p><small>{{r.created_at|date:'mediumDate'}}</small><div><button class="link-button" (click)="edit(r)">Edit</button><button class="link-button danger" (click)="remove(r)">Delete</button></div></article>}@empty{<div class="empty compact">No reviews yet. Delivered orders are eligible for review.</div>}</div></section>`})
export class ReviewsComponent implements OnInit{reviews=signal<Review[]>([]);eligible=signal<Order[]>([]);editingId=0;draft:Partial<Review>={order:undefined,rating:5,comment:''};constructor(private api:ApiService,private auth:AuthService,private toast:ToastService){}ngOnInit(){this.load();this.api.orders({status:'delivered'}).subscribe(v=>this.eligible.set(v.results));}load(){const user=this.auth.user();this.api.reviews(user?{customer:user.id}:{}).subscribe(v=>this.reviews.set(v.results));}stars(n:number){return '★'.repeat(n)+'☆'.repeat(5-n);}save(){const order=this.eligible().find(o=>o.id===this.draft.order);if(!order)return;const payload={...this.draft,restaurant:order.restaurant};const req=this.editingId?this.api.updateReview(this.editingId,payload):this.api.createReview(payload);req.subscribe(()=>{this.toast.show(this.editingId?'Review updated':'Review submitted');this.editingId=0;this.draft={order:undefined,rating:5,comment:''};this.load();});}edit(r:Review){this.editingId=r.id;this.draft={order:r.order,rating:r.rating,comment:r.comment,restaurant:r.restaurant};window.scrollTo({top:0,behavior:'smooth'});}remove(r:Review){if(confirm('Delete this review?'))this.api.deleteReview(r.id).subscribe(()=>{this.toast.show('Review deleted','info');this.load();});}}
