import { Component, OnInit, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { CartItem, FoodItem, Restaurant } from '../core/models/models';
import { ApiService } from '../core/services/api.service';
import { AuthService } from '../core/services/auth.service';
import { ToastService } from '../core/services/toast.service';
import { LoadingComponent } from '../shared/components/loading';
@Component({imports:[LoadingComponent],template:`@if(restaurant();as r){<section class="restaurant-hero"><div class="container"><div class="restaurant-symbol">{{r.cuisine_type.includes('Pizza')?'🍕':r.cuisine_type.includes('Biryani')?'🍛':'🍲'}}</div><div><span class="status" [class.open]="r.is_open">{{r.is_open?'OPEN NOW':'CLOSED'}}</span><h1>{{r.name}}</h1><p>{{r.cuisine_type}} · {{r.city}}</p><div class="hero-meta"><b>★ {{r.average_rating}}</b><span>{{r.estimated_delivery_time}} min</span><span>₹{{r.delivery_fee}} delivery</span><span>Min ₹{{r.minimum_order}}</span></div></div></div></section><section class="section container"><div class="section-head"><div><span class="eyebrow">THE MENU</span><h2>Freshly made for you</h2></div></div>@if(loading()){<app-loading/>}@else{<div class="food-grid">@for(f of foods();track f.id){<article class="food-card"><div class="food-icon">@if(foodImage(f);as image){<img [src]="image" [alt]="f.name">}@else{<span>{{f.is_vegetarian?'🥬':'🍗'}}</span>}</div><div><span class="veg" [class.nonveg]="!f.is_vegetarian"></span><h3>{{f.name}}</h3><p>{{f.description}}</p><small>★ {{f.rating}} · {{f.preparation_time}} min</small><div class="price-row"><b>₹{{f.price}}</b>@if(f.discount_price){<del>₹{{f.original_price}}</del>}@if(cartItem(f.id);as item){<div class="qty compact-qty"><button (click)="decrease(f)">−</button><span>{{item.quantity}}</span><button (click)="add(f)">+</button></div>}@else{<button class="btn small" [disabled]="!f.is_available" (click)="add(f)">{{f.is_available?'Add +':'Unavailable'}}</button>}</div></div></article>}</div>}</section>}@else{<app-loading/>}`})
export class RestaurantDetailComponent implements OnInit{restaurant=signal<Restaurant|null>(null);foods=signal<FoodItem[]>([]);cartItems=signal<Record<number,CartItem>>({});loading=signal(true);id=0;private readonly foodImages:Record<string,string>={'Chicken Biryani':'/images/food/chicken-biryani.webp','Veg Biryani':'/images/food/veg-biryani.webp','Mutton Biryani':'/images/food/mutton-biryani.webp','Margherita Pizza':'/images/food/margherita-pizza.webp','Chicken Pizza':'/images/food/chicken-pizza.webp','Farmhouse Pizza':'/images/food/farmhouse-pizza.webp'};private readonly categoryImages:Record<string,string>={'Biryani':'/images/food/chicken-biryani.webp','Pizza':'/images/food/margherita-pizza.webp','Burger':'/images/food/burger.webp','Fast Food':'/images/food/burger.webp','Chinese':'/images/food/chinese.webp','South Indian':'/images/food/south-indian.webp','North Indian':'/images/food/north-indian.webp','Desserts':'/images/food/desserts.webp','Beverages':'/images/food/drinks.webp','Seafood':'/images/food/seafood.webp'};constructor(private route:ActivatedRoute,private api:ApiService,private auth:AuthService,private router:Router,private toast:ToastService){}ngOnInit(){this.id=Number(this.route.snapshot.paramMap.get('id'));this.api.restaurant(this.id).subscribe(v=>this.restaurant.set(v));this.api.foods({restaurant:this.id,ordering:'category'}).subscribe(v=>{this.foods.set(v.results);this.loading.set(false)});if(this.auth.loggedIn())this.api.cart().subscribe(v=>this.cartItems.set(Object.fromEntries(v.items.map(item=>[item.food_item,item]))));}foodImage(f:FoodItem){return f.image||this.foodImages[f.name]||this.categoryImages[f.category_name]||'/images/food/veg-biryani.webp';}cartItem(foodId:number){return this.cartItems()[foodId];}private remember(item:CartItem){this.cartItems.update(items=>({...items,[item.food_item]:item}));}add(f:FoodItem){if(!this.auth.loggedIn()){void this.router.navigateByUrl('/login');return;}this.api.addToCart(f.id).subscribe({next:item=>{this.remember(item);this.toast.show(`${f.name} added to cart`);},error:e=>{if(e.error?.error?.details?.restaurant_conflict&&confirm('Replace your current cart with items from this restaurant?'))this.api.addToCart(f.id,1,true).subscribe(item=>{this.cartItems.set({[item.food_item]:item});this.toast.show('Cart replaced');});}});}decrease(f:FoodItem){const item=this.cartItem(f.id);if(!item)return;if(item.quantity===1){this.api.removeCartItem(item.id).subscribe(()=>this.cartItems.update(items=>{const next={...items};delete next[f.id];return next;}));return;}this.api.updateCartItem(item.id,item.quantity-1).subscribe(updated=>this.remember(updated));}}
